// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobs.sql

package sqlitedb

import (
	"context"
)

const createBlob = `-- name: CreateBlob :one
INSERT INTO blobs (
  id, document_id, filename, mime_type, size, sha256, data, created_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7, ?8
) RETURNING id, document_id, filename, mime_type, size, sha256, data, created_at
`

type CreateBlobParams struct {
	ID         string `json:"id"`
	DocumentID string `json:"document_id"`
	Filename   string `json:"filename"`
	MimeType   string `json:"mime_type"`
	Size       int64  `json:"size"`
	Sha256     string `json:"sha256"`
	Data       []byte `json:"data"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) CreateBlob(ctx context.Context, arg CreateBlobParams) (Blob, error) {
	row := q.db.QueryRowContext(ctx, createBlob,
		arg.ID,
		arg.DocumentID,
		arg.Filename,
		arg.MimeType,
		arg.Size,
		arg.Sha256,
		arg.Data,
		arg.CreatedAt,
	)
	var i Blob
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.Sha256,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocumentBlobs = `-- name: DeleteDocumentBlobs :exec
DELETE FROM blobs WHERE document_id = ?1
`

func (q *Queries) DeleteDocumentBlobs(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentBlobs, documentID)
	return err
}

const listDocumentBlobs = `-- name: ListDocumentBlobs :many
SELECT id, document_id, filename, mime_type, size, sha256, data, created_at FROM blobs
WHERE document_id = ?1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListDocumentBlobs(ctx context.Context, documentID string) ([]Blob, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentBlobs, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Blob{}
	for rows.Next() {
		var i Blob
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Filename,
			&i.MimeType,
			&i.Size,
			&i.Sha256,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
