// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents_count.sql

package sqlitedb

import (
	"context"
)

const countDocumentIDs = `-- name: CountDocumentIDs :one
WITH RECURSIVE folder_scope(id) AS (
  SELECT ?3 WHERE ?3 IS NOT NULL
  UNION ALL
  SELECT folders.id FROM folders
  JOIN folder_scope ON folders.parent_id = folder_scope.id
  WHERE ?8 != 0
),
trash_scope(id) AS (
  SELECT folders.id FROM folders WHERE folders.system_role = 'trash'
  UNION ALL
  SELECT folders.id FROM folders
  JOIN trash_scope ON folders.parent_id = trash_scope.id
)
SELECT COUNT(*)
FROM documents
WHERE (?1 != 0 OR documents.deleted_at IS NULL)
  AND (
    ?2 != 0 OR ?3 IS NOT NULL OR NOT EXISTS (
      SELECT 1 FROM trash_scope
      WHERE trash_scope.id = documents.folder_id
    )
  )
  AND (?4 IS NULL OR documents.status = ?4)
  AND (?5 IS NULL OR documents.kind = ?5)
  AND (?3 IS NULL OR documents.folder_id IN (SELECT id FROM folder_scope))
  AND (?6 <= 0 OR documents.rating >= ?6)
  AND (
    ?7 IS NULL OR EXISTS (
      SELECT 1 FROM document_tags
      JOIN tags ON tags.id = document_tags.tag_id
      WHERE document_tags.document_id = documents.id
        AND tags.slug = ?7
    )
  )
`

type CountDocumentIDsParams struct {
	IncludeDeleted           interface{} `json:"include_deleted"`
	IncludeTrash             interface{} `json:"include_trash"`
	FolderID                 interface{} `json:"folder_id"`
	Status                   interface{} `json:"status"`
	Kind                     interface{} `json:"kind"`
	RatingMin                interface{} `json:"rating_min"`
	Tag                      interface{} `json:"tag"`
	IncludeFolderDescendants interface{} `json:"include_folder_descendants"`
}

func (q *Queries) CountDocumentIDs(ctx context.Context, arg CountDocumentIDsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocumentIDs,
		arg.IncludeDeleted,
		arg.IncludeTrash,
		arg.FolderID,
		arg.Status,
		arg.Kind,
		arg.RatingMin,
		arg.Tag,
		arg.IncludeFolderDescendants,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchDocumentIDs = `-- name: CountSearchDocumentIDs :one
WITH RECURSIVE folder_scope(id) AS (
  SELECT ?4 WHERE ?4 IS NOT NULL
  UNION ALL
  SELECT folders.id FROM folders
  JOIN folder_scope ON folders.parent_id = folder_scope.id
  WHERE ?9 != 0
),
trash_scope(id) AS (
  SELECT folders.id FROM folders WHERE folders.system_role = 'trash'
  UNION ALL
  SELECT folders.id FROM folders
  JOIN trash_scope ON folders.parent_id = trash_scope.id
)
SELECT COUNT(*)
FROM documents_fts(?1) AS matches
JOIN documents ON documents.id = matches.document_id
WHERE (?2 != 0 OR documents.deleted_at IS NULL)
  AND (
    ?3 != 0 OR ?4 IS NOT NULL OR NOT EXISTS (
      SELECT 1 FROM trash_scope
      WHERE trash_scope.id = documents.folder_id
    )
  )
  AND (?5 IS NULL OR documents.status = ?5)
  AND (?6 IS NULL OR documents.kind = ?6)
  AND (?4 IS NULL OR documents.folder_id IN (SELECT id FROM folder_scope))
  AND (?7 <= 0 OR documents.rating >= ?7)
  AND (
    ?8 IS NULL OR EXISTS (
      SELECT 1 FROM document_tags
      JOIN tags ON tags.id = document_tags.tag_id
      WHERE document_tags.document_id = documents.id
        AND tags.slug = ?8
    )
  )
`

type CountSearchDocumentIDsParams struct {
	Query                    interface{} `json:"query"`
	IncludeDeleted           interface{} `json:"include_deleted"`
	IncludeTrash             interface{} `json:"include_trash"`
	FolderID                 interface{} `json:"folder_id"`
	Status                   interface{} `json:"status"`
	Kind                     interface{} `json:"kind"`
	RatingMin                interface{} `json:"rating_min"`
	Tag                      interface{} `json:"tag"`
	IncludeFolderDescendants interface{} `json:"include_folder_descendants"`
}

func (q *Queries) CountSearchDocumentIDs(ctx context.Context, arg CountSearchDocumentIDsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSearchDocumentIDs,
		arg.Query,
		arg.IncludeDeleted,
		arg.IncludeTrash,
		arg.FolderID,
		arg.Status,
		arg.Kind,
		arg.RatingMin,
		arg.Tag,
		arg.IncludeFolderDescendants,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}
