// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents_search.sql

package sqlitedb

import (
	"context"
)

const listDocumentIDsCreatedDesc = `-- name: ListDocumentIDsCreatedDesc :many
WITH RECURSIVE folder_scope(id) AS (
  SELECT ?3 WHERE ?3 IS NOT NULL
  UNION ALL
  SELECT folders.id FROM folders
  JOIN folder_scope ON folders.parent_id = folder_scope.id
  WHERE ?10 != 0
),
trash_scope(id) AS (
  SELECT folders.id FROM folders WHERE folders.system_role = 'trash'
  UNION ALL
  SELECT folders.id FROM folders
  JOIN trash_scope ON folders.parent_id = trash_scope.id
),
cursor_doc AS (
  SELECT id, title, kind, folder_id, canonical_url, source_url, language, status, rating, created_at, updated_at, read_at, deleted_at FROM documents WHERE id = ?8
)
SELECT documents.id
FROM documents
WHERE (?1 != 0 OR documents.deleted_at IS NULL)
  AND (
    ?2 != 0 OR ?3 IS NOT NULL OR NOT EXISTS (
      SELECT 1 FROM trash_scope
      WHERE trash_scope.id = documents.folder_id
    )
  )
  AND (?4 IS NULL OR documents.status = ?4)
  AND (?5 IS NULL OR documents.kind = ?5)
  AND (?3 IS NULL OR documents.folder_id IN (SELECT id FROM folder_scope))
  AND (?6 <= 0 OR documents.rating >= ?6)
  AND (
    ?7 IS NULL OR EXISTS (
      SELECT 1 FROM document_tags
      JOIN tags ON tags.id = document_tags.tag_id
      WHERE document_tags.document_id = documents.id
        AND tags.slug = ?7
    )
  )
  AND (
    ?8 IS NULL OR EXISTS (
      SELECT 1 FROM cursor_doc
      WHERE documents.created_at < cursor_doc.created_at
        OR (
          documents.created_at = cursor_doc.created_at
          AND documents.id < cursor_doc.id
        )
    )
  )
ORDER BY documents.created_at DESC, documents.id DESC
LIMIT ?9
`

type ListDocumentIDsCreatedDescParams struct {
	IncludeDeleted           interface{} `json:"include_deleted"`
	IncludeTrash             interface{} `json:"include_trash"`
	FolderID                 interface{} `json:"folder_id"`
	Status                   interface{} `json:"status"`
	Kind                     interface{} `json:"kind"`
	RatingMin                interface{} `json:"rating_min"`
	Tag                      interface{} `json:"tag"`
	CursorID                 interface{} `json:"cursor_id"`
	LimitRows                int64       `json:"limit_rows"`
	IncludeFolderDescendants interface{} `json:"include_folder_descendants"`
}

func (q *Queries) ListDocumentIDsCreatedDesc(ctx context.Context, arg ListDocumentIDsCreatedDescParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentIDsCreatedDesc,
		arg.IncludeDeleted,
		arg.IncludeTrash,
		arg.FolderID,
		arg.Status,
		arg.Kind,
		arg.RatingMin,
		arg.Tag,
		arg.CursorID,
		arg.LimitRows,
		arg.IncludeFolderDescendants,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentIDsRatingDesc = `-- name: ListDocumentIDsRatingDesc :many
WITH RECURSIVE folder_scope(id) AS (
  SELECT ?3 WHERE ?3 IS NOT NULL
  UNION ALL
  SELECT folders.id FROM folders
  JOIN folder_scope ON folders.parent_id = folder_scope.id
  WHERE ?10 != 0
),
trash_scope(id) AS (
  SELECT folders.id FROM folders WHERE folders.system_role = 'trash'
  UNION ALL
  SELECT folders.id FROM folders
  JOIN trash_scope ON folders.parent_id = trash_scope.id
),
cursor_doc AS (
  SELECT id, title, kind, folder_id, canonical_url, source_url, language, status, rating, created_at, updated_at, read_at, deleted_at FROM documents WHERE id = ?8
)
SELECT documents.id
FROM documents
WHERE (?1 != 0 OR documents.deleted_at IS NULL)
  AND (
    ?2 != 0 OR ?3 IS NOT NULL OR NOT EXISTS (
      SELECT 1 FROM trash_scope
      WHERE trash_scope.id = documents.folder_id
    )
  )
  AND (?4 IS NULL OR documents.status = ?4)
  AND (?5 IS NULL OR documents.kind = ?5)
  AND (?3 IS NULL OR documents.folder_id IN (SELECT id FROM folder_scope))
  AND (?6 <= 0 OR documents.rating >= ?6)
  AND (
    ?7 IS NULL OR EXISTS (
      SELECT 1 FROM document_tags
      JOIN tags ON tags.id = document_tags.tag_id
      WHERE document_tags.document_id = documents.id
        AND tags.slug = ?7
    )
  )
  AND (
    ?8 IS NULL OR EXISTS (
      SELECT 1 FROM cursor_doc
      WHERE COALESCE(documents.rating, 0) < COALESCE(cursor_doc.rating, 0)
        OR (
          COALESCE(documents.rating, 0) = COALESCE(cursor_doc.rating, 0)
          AND documents.updated_at < cursor_doc.updated_at
        )
        OR (
          COALESCE(documents.rating, 0) = COALESCE(cursor_doc.rating, 0)
          AND documents.updated_at = cursor_doc.updated_at
          AND documents.created_at < cursor_doc.created_at
        )
        OR (
          COALESCE(documents.rating, 0) = COALESCE(cursor_doc.rating, 0)
          AND documents.updated_at = cursor_doc.updated_at
          AND documents.created_at = cursor_doc.created_at
          AND documents.id < cursor_doc.id
        )
    )
  )
ORDER BY COALESCE(documents.rating, 0) DESC, documents.updated_at DESC,
  documents.created_at DESC, documents.id DESC
LIMIT ?9
`

type ListDocumentIDsRatingDescParams struct {
	IncludeDeleted           interface{} `json:"include_deleted"`
	IncludeTrash             interface{} `json:"include_trash"`
	FolderID                 interface{} `json:"folder_id"`
	Status                   interface{} `json:"status"`
	Kind                     interface{} `json:"kind"`
	RatingMin                interface{} `json:"rating_min"`
	Tag                      interface{} `json:"tag"`
	CursorID                 interface{} `json:"cursor_id"`
	LimitRows                int64       `json:"limit_rows"`
	IncludeFolderDescendants interface{} `json:"include_folder_descendants"`
}

func (q *Queries) ListDocumentIDsRatingDesc(ctx context.Context, arg ListDocumentIDsRatingDescParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentIDsRatingDesc,
		arg.IncludeDeleted,
		arg.IncludeTrash,
		arg.FolderID,
		arg.Status,
		arg.Kind,
		arg.RatingMin,
		arg.Tag,
		arg.CursorID,
		arg.LimitRows,
		arg.IncludeFolderDescendants,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentIDsRecent = `-- name: ListDocumentIDsRecent :many
WITH RECURSIVE folder_scope(id) AS (
  SELECT ?3 WHERE ?3 IS NOT NULL
  UNION ALL
  SELECT folders.id FROM folders
  JOIN folder_scope ON folders.parent_id = folder_scope.id
  WHERE ?10 != 0
),
trash_scope(id) AS (
  SELECT folders.id FROM folders WHERE folders.system_role = 'trash'
  UNION ALL
  SELECT folders.id FROM folders
  JOIN trash_scope ON folders.parent_id = trash_scope.id
),
cursor_doc AS (
  SELECT id, title, kind, folder_id, canonical_url, source_url, language, status, rating, created_at, updated_at, read_at, deleted_at FROM documents WHERE id = ?8
)
SELECT documents.id
FROM documents
WHERE (?1 != 0 OR documents.deleted_at IS NULL)
  AND (
    ?2 != 0 OR ?3 IS NOT NULL OR NOT EXISTS (
      SELECT 1 FROM trash_scope
      WHERE trash_scope.id = documents.folder_id
    )
  )
  AND (?4 IS NULL OR documents.status = ?4)
  AND (?5 IS NULL OR documents.kind = ?5)
  AND (?3 IS NULL OR documents.folder_id IN (SELECT id FROM folder_scope))
  AND (?6 <= 0 OR documents.rating >= ?6)
  AND (
    ?7 IS NULL OR EXISTS (
      SELECT 1 FROM document_tags
      JOIN tags ON tags.id = document_tags.tag_id
      WHERE document_tags.document_id = documents.id
        AND tags.slug = ?7
    )
  )
  AND (
    ?8 IS NULL OR EXISTS (
      SELECT 1 FROM cursor_doc
      WHERE documents.updated_at < cursor_doc.updated_at
        OR (
          documents.updated_at = cursor_doc.updated_at
          AND documents.created_at < cursor_doc.created_at
        )
        OR (
          documents.updated_at = cursor_doc.updated_at
          AND documents.created_at = cursor_doc.created_at
          AND documents.id < cursor_doc.id
        )
    )
  )
ORDER BY documents.updated_at DESC, documents.created_at DESC, documents.id DESC
LIMIT ?9
`

type ListDocumentIDsRecentParams struct {
	IncludeDeleted           interface{} `json:"include_deleted"`
	IncludeTrash             interface{} `json:"include_trash"`
	FolderID                 interface{} `json:"folder_id"`
	Status                   interface{} `json:"status"`
	Kind                     interface{} `json:"kind"`
	RatingMin                interface{} `json:"rating_min"`
	Tag                      interface{} `json:"tag"`
	CursorID                 interface{} `json:"cursor_id"`
	LimitRows                int64       `json:"limit_rows"`
	IncludeFolderDescendants interface{} `json:"include_folder_descendants"`
}

func (q *Queries) ListDocumentIDsRecent(ctx context.Context, arg ListDocumentIDsRecentParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentIDsRecent,
		arg.IncludeDeleted,
		arg.IncludeTrash,
		arg.FolderID,
		arg.Status,
		arg.Kind,
		arg.RatingMin,
		arg.Tag,
		arg.CursorID,
		arg.LimitRows,
		arg.IncludeFolderDescendants,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentIDsCreatedDesc = `-- name: SearchDocumentIDsCreatedDesc :many
WITH RECURSIVE folder_scope(id) AS (
  SELECT ?4 WHERE ?4 IS NOT NULL
  UNION ALL
  SELECT folders.id FROM folders
  JOIN folder_scope ON folders.parent_id = folder_scope.id
  WHERE ?11 != 0
),
trash_scope(id) AS (
  SELECT folders.id FROM folders WHERE folders.system_role = 'trash'
  UNION ALL
  SELECT folders.id FROM folders
  JOIN trash_scope ON folders.parent_id = trash_scope.id
),
cursor_doc AS (
  SELECT id, title, kind, folder_id, canonical_url, source_url, language, status, rating, created_at, updated_at, read_at, deleted_at FROM documents WHERE id = ?9
)
SELECT documents.id
FROM documents_fts(?1) AS matches
JOIN documents ON documents.id = matches.document_id
WHERE (?2 != 0 OR documents.deleted_at IS NULL)
  AND (
    ?3 != 0 OR ?4 IS NOT NULL OR NOT EXISTS (
      SELECT 1 FROM trash_scope
      WHERE trash_scope.id = documents.folder_id
    )
  )
  AND (?5 IS NULL OR documents.status = ?5)
  AND (?6 IS NULL OR documents.kind = ?6)
  AND (?4 IS NULL OR documents.folder_id IN (SELECT id FROM folder_scope))
  AND (?7 <= 0 OR documents.rating >= ?7)
  AND (
    ?8 IS NULL OR EXISTS (
      SELECT 1 FROM document_tags
      JOIN tags ON tags.id = document_tags.tag_id
      WHERE document_tags.document_id = documents.id
        AND tags.slug = ?8
    )
  )
  AND (
    ?9 IS NULL OR EXISTS (
      SELECT 1 FROM cursor_doc
      WHERE documents.created_at < cursor_doc.created_at
        OR (
          documents.created_at = cursor_doc.created_at
          AND documents.id < cursor_doc.id
        )
    )
  )
ORDER BY documents.created_at DESC, documents.id DESC
LIMIT ?10
`

type SearchDocumentIDsCreatedDescParams struct {
	Query                    interface{} `json:"query"`
	IncludeDeleted           interface{} `json:"include_deleted"`
	IncludeTrash             interface{} `json:"include_trash"`
	FolderID                 interface{} `json:"folder_id"`
	Status                   interface{} `json:"status"`
	Kind                     interface{} `json:"kind"`
	RatingMin                interface{} `json:"rating_min"`
	Tag                      interface{} `json:"tag"`
	CursorID                 interface{} `json:"cursor_id"`
	LimitRows                int64       `json:"limit_rows"`
	IncludeFolderDescendants interface{} `json:"include_folder_descendants"`
}

func (q *Queries) SearchDocumentIDsCreatedDesc(ctx context.Context, arg SearchDocumentIDsCreatedDescParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, searchDocumentIDsCreatedDesc,
		arg.Query,
		arg.IncludeDeleted,
		arg.IncludeTrash,
		arg.FolderID,
		arg.Status,
		arg.Kind,
		arg.RatingMin,
		arg.Tag,
		arg.CursorID,
		arg.LimitRows,
		arg.IncludeFolderDescendants,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentIDsRatingDesc = `-- name: SearchDocumentIDsRatingDesc :many
WITH RECURSIVE folder_scope(id) AS (
  SELECT ?4 WHERE ?4 IS NOT NULL
  UNION ALL
  SELECT folders.id FROM folders
  JOIN folder_scope ON folders.parent_id = folder_scope.id
  WHERE ?11 != 0
),
trash_scope(id) AS (
  SELECT folders.id FROM folders WHERE folders.system_role = 'trash'
  UNION ALL
  SELECT folders.id FROM folders
  JOIN trash_scope ON folders.parent_id = trash_scope.id
),
cursor_doc AS (
  SELECT id, title, kind, folder_id, canonical_url, source_url, language, status, rating, created_at, updated_at, read_at, deleted_at FROM documents WHERE id = ?9
)
SELECT documents.id
FROM documents_fts(?1) AS matches
JOIN documents ON documents.id = matches.document_id
WHERE (?2 != 0 OR documents.deleted_at IS NULL)
  AND (
    ?3 != 0 OR ?4 IS NOT NULL OR NOT EXISTS (
      SELECT 1 FROM trash_scope
      WHERE trash_scope.id = documents.folder_id
    )
  )
  AND (?5 IS NULL OR documents.status = ?5)
  AND (?6 IS NULL OR documents.kind = ?6)
  AND (?4 IS NULL OR documents.folder_id IN (SELECT id FROM folder_scope))
  AND (?7 <= 0 OR documents.rating >= ?7)
  AND (
    ?8 IS NULL OR EXISTS (
      SELECT 1 FROM document_tags
      JOIN tags ON tags.id = document_tags.tag_id
      WHERE document_tags.document_id = documents.id
        AND tags.slug = ?8
    )
  )
  AND (
    ?9 IS NULL OR EXISTS (
      SELECT 1 FROM cursor_doc
      WHERE COALESCE(documents.rating, 0) < COALESCE(cursor_doc.rating, 0)
        OR (
          COALESCE(documents.rating, 0) = COALESCE(cursor_doc.rating, 0)
          AND documents.updated_at < cursor_doc.updated_at
        )
        OR (
          COALESCE(documents.rating, 0) = COALESCE(cursor_doc.rating, 0)
          AND documents.updated_at = cursor_doc.updated_at
          AND documents.created_at < cursor_doc.created_at
        )
        OR (
          COALESCE(documents.rating, 0) = COALESCE(cursor_doc.rating, 0)
          AND documents.updated_at = cursor_doc.updated_at
          AND documents.created_at = cursor_doc.created_at
          AND documents.id < cursor_doc.id
        )
    )
  )
ORDER BY COALESCE(documents.rating, 0) DESC, documents.updated_at DESC,
  documents.created_at DESC, documents.id DESC
LIMIT ?10
`

type SearchDocumentIDsRatingDescParams struct {
	Query                    interface{} `json:"query"`
	IncludeDeleted           interface{} `json:"include_deleted"`
	IncludeTrash             interface{} `json:"include_trash"`
	FolderID                 interface{} `json:"folder_id"`
	Status                   interface{} `json:"status"`
	Kind                     interface{} `json:"kind"`
	RatingMin                interface{} `json:"rating_min"`
	Tag                      interface{} `json:"tag"`
	CursorID                 interface{} `json:"cursor_id"`
	LimitRows                int64       `json:"limit_rows"`
	IncludeFolderDescendants interface{} `json:"include_folder_descendants"`
}

func (q *Queries) SearchDocumentIDsRatingDesc(ctx context.Context, arg SearchDocumentIDsRatingDescParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, searchDocumentIDsRatingDesc,
		arg.Query,
		arg.IncludeDeleted,
		arg.IncludeTrash,
		arg.FolderID,
		arg.Status,
		arg.Kind,
		arg.RatingMin,
		arg.Tag,
		arg.CursorID,
		arg.LimitRows,
		arg.IncludeFolderDescendants,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentIDsRecent = `-- name: SearchDocumentIDsRecent :many
WITH RECURSIVE folder_scope(id) AS (
  SELECT ?4 WHERE ?4 IS NOT NULL
  UNION ALL
  SELECT folders.id FROM folders
  JOIN folder_scope ON folders.parent_id = folder_scope.id
  WHERE ?11 != 0
),
trash_scope(id) AS (
  SELECT folders.id FROM folders WHERE folders.system_role = 'trash'
  UNION ALL
  SELECT folders.id FROM folders
  JOIN trash_scope ON folders.parent_id = trash_scope.id
),
cursor_doc AS (
  SELECT id, title, kind, folder_id, canonical_url, source_url, language, status, rating, created_at, updated_at, read_at, deleted_at FROM documents WHERE id = ?9
)
SELECT documents.id
FROM documents_fts(?1) AS matches
JOIN documents ON documents.id = matches.document_id
WHERE (?2 != 0 OR documents.deleted_at IS NULL)
  AND (
    ?3 != 0 OR ?4 IS NOT NULL OR NOT EXISTS (
      SELECT 1 FROM trash_scope
      WHERE trash_scope.id = documents.folder_id
    )
  )
  AND (?5 IS NULL OR documents.status = ?5)
  AND (?6 IS NULL OR documents.kind = ?6)
  AND (?4 IS NULL OR documents.folder_id IN (SELECT id FROM folder_scope))
  AND (?7 <= 0 OR documents.rating >= ?7)
  AND (
    ?8 IS NULL OR EXISTS (
      SELECT 1 FROM document_tags
      JOIN tags ON tags.id = document_tags.tag_id
      WHERE document_tags.document_id = documents.id
        AND tags.slug = ?8
    )
  )
  AND (
    ?9 IS NULL OR EXISTS (
      SELECT 1 FROM cursor_doc
      WHERE documents.updated_at < cursor_doc.updated_at
        OR (
          documents.updated_at = cursor_doc.updated_at
          AND documents.created_at < cursor_doc.created_at
        )
        OR (
          documents.updated_at = cursor_doc.updated_at
          AND documents.created_at = cursor_doc.created_at
          AND documents.id < cursor_doc.id
        )
    )
  )
ORDER BY documents.updated_at DESC, documents.created_at DESC, documents.id DESC
LIMIT ?10
`

type SearchDocumentIDsRecentParams struct {
	Query                    interface{} `json:"query"`
	IncludeDeleted           interface{} `json:"include_deleted"`
	IncludeTrash             interface{} `json:"include_trash"`
	FolderID                 interface{} `json:"folder_id"`
	Status                   interface{} `json:"status"`
	Kind                     interface{} `json:"kind"`
	RatingMin                interface{} `json:"rating_min"`
	Tag                      interface{} `json:"tag"`
	CursorID                 interface{} `json:"cursor_id"`
	LimitRows                int64       `json:"limit_rows"`
	IncludeFolderDescendants interface{} `json:"include_folder_descendants"`
}

func (q *Queries) SearchDocumentIDsRecent(ctx context.Context, arg SearchDocumentIDsRecentParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, searchDocumentIDsRecent,
		arg.Query,
		arg.IncludeDeleted,
		arg.IncludeTrash,
		arg.FolderID,
		arg.Status,
		arg.Kind,
		arg.RatingMin,
		arg.Tag,
		arg.CursorID,
		arg.LimitRows,
		arg.IncludeFolderDescendants,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDocumentIDsRelevance = `-- name: SearchDocumentIDsRelevance :many
WITH RECURSIVE folder_scope(id) AS (
  SELECT ?4 WHERE ?4 IS NOT NULL
  UNION ALL
  SELECT folders.id FROM folders
  JOIN folder_scope ON folders.parent_id = folder_scope.id
  WHERE ?11 != 0
),
trash_scope(id) AS (
  SELECT folders.id FROM folders WHERE folders.system_role = 'trash'
  UNION ALL
  SELECT folders.id FROM folders
  JOIN trash_scope ON folders.parent_id = trash_scope.id
),
cursor_doc AS (
  SELECT cursor_documents.id, cursor_documents.title, cursor_documents.kind, cursor_documents.folder_id, cursor_documents.canonical_url, cursor_documents.source_url, cursor_documents.language, cursor_documents.status, cursor_documents.rating, cursor_documents.created_at, cursor_documents.updated_at, cursor_documents.read_at, cursor_documents.deleted_at, bm25(documents_fts) AS cursor_rank
  FROM documents_fts(?1) AS cursor_matches
  JOIN documents AS cursor_documents ON cursor_documents.id = cursor_matches.document_id
  WHERE cursor_documents.id = ?9
)
SELECT documents.id
FROM documents_fts(?1) AS matches
JOIN documents ON documents.id = matches.document_id
WHERE (?2 != 0 OR documents.deleted_at IS NULL)
  AND (
    ?3 != 0 OR ?4 IS NOT NULL OR NOT EXISTS (
      SELECT 1 FROM trash_scope
      WHERE trash_scope.id = documents.folder_id
    )
  )
  AND (?5 IS NULL OR documents.status = ?5)
  AND (?6 IS NULL OR documents.kind = ?6)
  AND (?4 IS NULL OR documents.folder_id IN (SELECT id FROM folder_scope))
  AND (?7 <= 0 OR documents.rating >= ?7)
  AND (
    ?8 IS NULL OR EXISTS (
      SELECT 1 FROM document_tags
      JOIN tags ON tags.id = document_tags.tag_id
      WHERE document_tags.document_id = documents.id
        AND tags.slug = ?8
    )
  )
  AND (
    ?9 IS NULL OR EXISTS (
      SELECT 1 FROM cursor_doc
      WHERE bm25(documents_fts) > cursor_doc.cursor_rank
        OR (
          bm25(documents_fts) = cursor_doc.cursor_rank
          AND documents.updated_at < cursor_doc.updated_at
        )
        OR (
          bm25(documents_fts) = cursor_doc.cursor_rank
          AND documents.updated_at = cursor_doc.updated_at
          AND documents.created_at < cursor_doc.created_at
        )
        OR (
          bm25(documents_fts) = cursor_doc.cursor_rank
          AND documents.updated_at = cursor_doc.updated_at
          AND documents.created_at = cursor_doc.created_at
          AND documents.id < cursor_doc.id
        )
    )
  )
ORDER BY bm25(documents_fts), documents.updated_at DESC, documents.created_at DESC,
  documents.id DESC
LIMIT ?10
`

type SearchDocumentIDsRelevanceParams struct {
	Query                    interface{} `json:"query"`
	IncludeDeleted           interface{} `json:"include_deleted"`
	IncludeTrash             interface{} `json:"include_trash"`
	FolderID                 interface{} `json:"folder_id"`
	Status                   interface{} `json:"status"`
	Kind                     interface{} `json:"kind"`
	RatingMin                interface{} `json:"rating_min"`
	Tag                      interface{} `json:"tag"`
	CursorID                 interface{} `json:"cursor_id"`
	LimitRows                int64       `json:"limit_rows"`
	IncludeFolderDescendants interface{} `json:"include_folder_descendants"`
}

func (q *Queries) SearchDocumentIDsRelevance(ctx context.Context, arg SearchDocumentIDsRelevanceParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, searchDocumentIDsRelevance,
		arg.Query,
		arg.IncludeDeleted,
		arg.IncludeTrash,
		arg.FolderID,
		arg.Status,
		arg.Kind,
		arg.RatingMin,
		arg.Tag,
		arg.CursorID,
		arg.LimitRows,
		arg.IncludeFolderDescendants,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
