// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_versions.sql

package sqlitedb

import (
	"context"
)

const createDocumentVersion = `-- name: CreateDocumentVersion :one
INSERT INTO document_versions (
  id, document_id, sequence, mutation_kind, title, content_snapshot_json,
  metadata_snapshot_json, created_at
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5, ?6,
  ?7, ?8
) RETURNING id, document_id, sequence, mutation_kind, title, content_snapshot_json, metadata_snapshot_json, created_at
`

type CreateDocumentVersionParams struct {
	ID                   string `json:"id"`
	DocumentID           string `json:"document_id"`
	Sequence             int64  `json:"sequence"`
	MutationKind         string `json:"mutation_kind"`
	Title                string `json:"title"`
	ContentSnapshotJson  string `json:"content_snapshot_json"`
	MetadataSnapshotJson string `json:"metadata_snapshot_json"`
	CreatedAt            int64  `json:"created_at"`
}

func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRowContext(ctx, createDocumentVersion,
		arg.ID,
		arg.DocumentID,
		arg.Sequence,
		arg.MutationKind,
		arg.Title,
		arg.ContentSnapshotJson,
		arg.MetadataSnapshotJson,
		arg.CreatedAt,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Sequence,
		&i.MutationKind,
		&i.Title,
		&i.ContentSnapshotJson,
		&i.MetadataSnapshotJson,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT id, document_id, sequence, mutation_kind, title, content_snapshot_json, metadata_snapshot_json, created_at FROM document_versions
WHERE document_id = ?1
ORDER BY sequence ASC, id ASC
`

func (q *Queries) ListDocumentVersions(ctx context.Context, documentID string) ([]DocumentVersion, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentVersions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentVersion{}
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Sequence,
			&i.MutationKind,
			&i.Title,
			&i.ContentSnapshotJson,
			&i.MetadataSnapshotJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
