// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
  id, title, kind, folder_id, canonical_url, source_url, language, status,
  rating, created_at, updated_at, read_at, deleted_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10,
  ?11, ?12, ?13
) RETURNING id, title, kind, folder_id, canonical_url, source_url, language, status, rating, created_at, updated_at, read_at, deleted_at
`

type CreateDocumentParams struct {
	ID           string         `json:"id"`
	Title        string         `json:"title"`
	Kind         string         `json:"kind"`
	FolderID     sql.NullString `json:"folder_id"`
	CanonicalUrl sql.NullString `json:"canonical_url"`
	SourceUrl    sql.NullString `json:"source_url"`
	Language     sql.NullString `json:"language"`
	Status       string         `json:"status"`
	Rating       sql.NullInt64  `json:"rating"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	ReadAt       sql.NullInt64  `json:"read_at"`
	DeletedAt    sql.NullInt64  `json:"deleted_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.ID,
		arg.Title,
		arg.Kind,
		arg.FolderID,
		arg.CanonicalUrl,
		arg.SourceUrl,
		arg.Language,
		arg.Status,
		arg.Rating,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ReadAt,
		arg.DeletedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Kind,
		&i.FolderID,
		&i.CanonicalUrl,
		&i.SourceUrl,
		&i.Language,
		&i.Status,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDocumentContent = `-- name: CreateDocumentContent :one
INSERT INTO document_contents (
  id, document_id, role, format, language, content, source_content_id, created_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8
) RETURNING id, document_id, role, format, language, content, source_content_id, created_at
`

type CreateDocumentContentParams struct {
	ID              string         `json:"id"`
	DocumentID      string         `json:"document_id"`
	Role            string         `json:"role"`
	Format          string         `json:"format"`
	Language        sql.NullString `json:"language"`
	Content         string         `json:"content"`
	SourceContentID sql.NullString `json:"source_content_id"`
	CreatedAt       int64          `json:"created_at"`
}

func (q *Queries) CreateDocumentContent(ctx context.Context, arg CreateDocumentContentParams) (DocumentContent, error) {
	row := q.db.QueryRowContext(ctx, createDocumentContent,
		arg.ID,
		arg.DocumentID,
		arg.Role,
		arg.Format,
		arg.Language,
		arg.Content,
		arg.SourceContentID,
		arg.CreatedAt,
	)
	var i DocumentContent
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Role,
		&i.Format,
		&i.Language,
		&i.Content,
		&i.SourceContentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocumentContents = `-- name: DeleteDocumentContents :exec
DELETE FROM document_contents WHERE document_id = ?1
`

func (q *Queries) DeleteDocumentContents(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentContents, documentID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, title, kind, folder_id, canonical_url, source_url, language, status, rating, created_at, updated_at, read_at, deleted_at FROM documents WHERE id = ?1
`

func (q *Queries) GetDocument(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Kind,
		&i.FolderID,
		&i.CanonicalUrl,
		&i.SourceUrl,
		&i.Language,
		&i.Status,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDocumentContents = `-- name: ListDocumentContents :many
SELECT id, document_id, role, format, language, content, source_content_id, created_at FROM document_contents
WHERE document_id = ?1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListDocumentContents(ctx context.Context, documentID string) ([]DocumentContent, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentContents, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentContent{}
	for rows.Next() {
		var i DocumentContent
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Role,
			&i.Format,
			&i.Language,
			&i.Content,
			&i.SourceContentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, title, kind, folder_id, canonical_url, source_url, language, status, rating, created_at, updated_at, read_at, deleted_at FROM documents ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDocuments(ctx context.Context) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Kind,
			&i.FolderID,
			&i.CanonicalUrl,
			&i.SourceUrl,
			&i.Language,
			&i.Status,
			&i.Rating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReadAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDocument = `-- name: SoftDeleteDocument :one
UPDATE documents
SET deleted_at = ?1,
    updated_at = ?2
WHERE id = ?3
RETURNING id, title, kind, folder_id, canonical_url, source_url, language, status, rating, created_at, updated_at, read_at, deleted_at
`

type SoftDeleteDocumentParams struct {
	DeletedAt sql.NullInt64 `json:"deleted_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, softDeleteDocument, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Kind,
		&i.FolderID,
		&i.CanonicalUrl,
		&i.SourceUrl,
		&i.Language,
		&i.Status,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDocumentMetadata = `-- name: UpdateDocumentMetadata :one
UPDATE documents
SET title = ?1,
    folder_id = ?2,
    updated_at = ?3
WHERE id = ?4
RETURNING id, title, kind, folder_id, canonical_url, source_url, language, status, rating, created_at, updated_at, read_at, deleted_at
`

type UpdateDocumentMetadataParams struct {
	Title     string         `json:"title"`
	FolderID  sql.NullString `json:"folder_id"`
	UpdatedAt int64          `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) UpdateDocumentMetadata(ctx context.Context, arg UpdateDocumentMetadataParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentMetadata,
		arg.Title,
		arg.FolderID,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Kind,
		&i.FolderID,
		&i.CanonicalUrl,
		&i.SourceUrl,
		&i.Language,
		&i.Status,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO documents (
  id, title, kind, folder_id, canonical_url, source_url, language, status,
  rating, created_at, updated_at, read_at, deleted_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10,
  ?11, ?12, ?13
)
ON CONFLICT(id) DO UPDATE SET
  title = excluded.title,
  kind = excluded.kind,
  folder_id = excluded.folder_id,
  canonical_url = excluded.canonical_url,
  source_url = excluded.source_url,
  language = excluded.language,
  status = excluded.status,
  rating = excluded.rating,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  read_at = excluded.read_at,
  deleted_at = excluded.deleted_at
RETURNING id, title, kind, folder_id, canonical_url, source_url, language, status, rating, created_at, updated_at, read_at, deleted_at
`

type UpsertDocumentParams struct {
	ID           string         `json:"id"`
	Title        string         `json:"title"`
	Kind         string         `json:"kind"`
	FolderID     sql.NullString `json:"folder_id"`
	CanonicalUrl sql.NullString `json:"canonical_url"`
	SourceUrl    sql.NullString `json:"source_url"`
	Language     sql.NullString `json:"language"`
	Status       string         `json:"status"`
	Rating       sql.NullInt64  `json:"rating"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	ReadAt       sql.NullInt64  `json:"read_at"`
	DeletedAt    sql.NullInt64  `json:"deleted_at"`
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, upsertDocument,
		arg.ID,
		arg.Title,
		arg.Kind,
		arg.FolderID,
		arg.CanonicalUrl,
		arg.SourceUrl,
		arg.Language,
		arg.Status,
		arg.Rating,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ReadAt,
		arg.DeletedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Kind,
		&i.FolderID,
		&i.CanonicalUrl,
		&i.SourceUrl,
		&i.Language,
		&i.Status,
		&i.Rating,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadAt,
		&i.DeletedAt,
	)
	return i, err
}
