// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (
  id, url, title, folder_id, enabled, last_checked_at, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8
) RETURNING id, url, title, folder_id, enabled, last_checked_at, created_at, updated_at
`

type CreateFeedParams struct {
	ID            string         `json:"id"`
	Url           string         `json:"url"`
	Title         sql.NullString `json:"title"`
	FolderID      sql.NullString `json:"folder_id"`
	Enabled       int64          `json:"enabled"`
	LastCheckedAt sql.NullInt64  `json:"last_checked_at"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.Url,
		arg.Title,
		arg.FolderID,
		arg.Enabled,
		arg.LastCheckedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.FolderID,
		&i.Enabled,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFeedItem = `-- name: CreateFeedItem :one
INSERT INTO feed_items (
  id, feed_id, document_id, guid, url, canonical_url, content_hash,
  published_at, created_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9
) RETURNING id, feed_id, document_id, guid, url, canonical_url, content_hash, published_at, created_at
`

type CreateFeedItemParams struct {
	ID           string         `json:"id"`
	FeedID       string         `json:"feed_id"`
	DocumentID   string         `json:"document_id"`
	Guid         sql.NullString `json:"guid"`
	Url          string         `json:"url"`
	CanonicalUrl sql.NullString `json:"canonical_url"`
	ContentHash  sql.NullString `json:"content_hash"`
	PublishedAt  sql.NullInt64  `json:"published_at"`
	CreatedAt    int64          `json:"created_at"`
}

func (q *Queries) CreateFeedItem(ctx context.Context, arg CreateFeedItemParams) (FeedItem, error) {
	row := q.db.QueryRowContext(ctx, createFeedItem,
		arg.ID,
		arg.FeedID,
		arg.DocumentID,
		arg.Guid,
		arg.Url,
		arg.CanonicalUrl,
		arg.ContentHash,
		arg.PublishedAt,
		arg.CreatedAt,
	)
	var i FeedItem
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.DocumentID,
		&i.Guid,
		&i.Url,
		&i.CanonicalUrl,
		&i.ContentHash,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFeed = `-- name: DeleteFeed :exec
DELETE FROM feeds WHERE id = ?1
`

func (q *Queries) DeleteFeed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFeed, id)
	return err
}

const getFeed = `-- name: GetFeed :one
SELECT id, url, title, folder_id, enabled, last_checked_at, created_at, updated_at FROM feeds WHERE id = ?1
`

func (q *Queries) GetFeed(ctx context.Context, id string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeed, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.FolderID,
		&i.Enabled,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedByURL = `-- name: GetFeedByURL :one
SELECT id, url, title, folder_id, enabled, last_checked_at, created_at, updated_at FROM feeds WHERE url = ?1
`

func (q *Queries) GetFeedByURL(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.FolderID,
		&i.Enabled,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeedItemByDocumentID = `-- name: GetFeedItemByDocumentID :one
SELECT id, feed_id, document_id, guid, url, canonical_url, content_hash, published_at, created_at FROM feed_items
WHERE document_id = ?1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetFeedItemByDocumentID(ctx context.Context, documentID string) (FeedItem, error) {
	row := q.db.QueryRowContext(ctx, getFeedItemByDocumentID, documentID)
	var i FeedItem
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.DocumentID,
		&i.Guid,
		&i.Url,
		&i.CanonicalUrl,
		&i.ContentHash,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listFeedItems = `-- name: ListFeedItems :many
SELECT id, feed_id, document_id, guid, url, canonical_url, content_hash, published_at, created_at FROM feed_items
WHERE feed_id = ?1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListFeedItems(ctx context.Context, feedID string) ([]FeedItem, error) {
	rows, err := q.db.QueryContext(ctx, listFeedItems, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeedItem{}
	for rows.Next() {
		var i FeedItem
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.DocumentID,
			&i.Guid,
			&i.Url,
			&i.CanonicalUrl,
			&i.ContentHash,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeeds = `-- name: ListFeeds :many
SELECT id, url, title, folder_id, enabled, last_checked_at, created_at, updated_at FROM feeds ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, listFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feed{}
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.FolderID,
			&i.Enabled,
			&i.LastCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeed = `-- name: UpsertFeed :one
INSERT INTO feeds (
  id, url, title, folder_id, enabled, last_checked_at, created_at, updated_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8
)
ON CONFLICT(id) DO UPDATE SET
  url = excluded.url,
  title = excluded.title,
  folder_id = excluded.folder_id,
  enabled = excluded.enabled,
  last_checked_at = excluded.last_checked_at,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at
RETURNING id, url, title, folder_id, enabled, last_checked_at, created_at, updated_at
`

type UpsertFeedParams struct {
	ID            string         `json:"id"`
	Url           string         `json:"url"`
	Title         sql.NullString `json:"title"`
	FolderID      sql.NullString `json:"folder_id"`
	Enabled       int64          `json:"enabled"`
	LastCheckedAt sql.NullInt64  `json:"last_checked_at"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

func (q *Queries) UpsertFeed(ctx context.Context, arg UpsertFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, upsertFeed,
		arg.ID,
		arg.Url,
		arg.Title,
		arg.FolderID,
		arg.Enabled,
		arg.LastCheckedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.FolderID,
		&i.Enabled,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFeedItem = `-- name: UpsertFeedItem :one
INSERT INTO feed_items (
  id, feed_id, document_id, guid, url, canonical_url, content_hash,
  published_at, created_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9
)
ON CONFLICT(id) DO UPDATE SET
  feed_id = excluded.feed_id,
  document_id = excluded.document_id,
  guid = excluded.guid,
  url = excluded.url,
  canonical_url = excluded.canonical_url,
  content_hash = excluded.content_hash,
  published_at = excluded.published_at,
  created_at = excluded.created_at
RETURNING id, feed_id, document_id, guid, url, canonical_url, content_hash, published_at, created_at
`

type UpsertFeedItemParams struct {
	ID           string         `json:"id"`
	FeedID       string         `json:"feed_id"`
	DocumentID   string         `json:"document_id"`
	Guid         sql.NullString `json:"guid"`
	Url          string         `json:"url"`
	CanonicalUrl sql.NullString `json:"canonical_url"`
	ContentHash  sql.NullString `json:"content_hash"`
	PublishedAt  sql.NullInt64  `json:"published_at"`
	CreatedAt    int64          `json:"created_at"`
}

func (q *Queries) UpsertFeedItem(ctx context.Context, arg UpsertFeedItemParams) (FeedItem, error) {
	row := q.db.QueryRowContext(ctx, upsertFeedItem,
		arg.ID,
		arg.FeedID,
		arg.DocumentID,
		arg.Guid,
		arg.Url,
		arg.CanonicalUrl,
		arg.ContentHash,
		arg.PublishedAt,
		arg.CreatedAt,
	)
	var i FeedItem
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.DocumentID,
		&i.Guid,
		&i.Url,
		&i.CanonicalUrl,
		&i.ContentHash,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}
