// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (
  id, parent_id, name, system_role, sort_order, created_at, updated_at
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5, ?6,
  ?7
) RETURNING id, parent_id, name, sort_order, created_at, updated_at, system_role
`

type CreateFolderParams struct {
	ID         string         `json:"id"`
	ParentID   sql.NullString `json:"parent_id"`
	Name       string         `json:"name"`
	SystemRole sql.NullString `json:"system_role"`
	SortOrder  int64          `json:"sort_order"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, createFolder,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.SystemRole,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemRole,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = ?1
`

func (q *Queries) DeleteFolder(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFolder, id)
	return err
}

const getFolder = `-- name: GetFolder :one
SELECT id, parent_id, name, sort_order, created_at, updated_at, system_role FROM folders WHERE id = ?1
`

func (q *Queries) GetFolder(ctx context.Context, id string) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemRole,
	)
	return i, err
}

const listFolders = `-- name: ListFolders :many
SELECT id, parent_id, name, sort_order, created_at, updated_at, system_role FROM folders ORDER BY parent_id, sort_order, name, id
`

func (q *Queries) ListFolders(ctx context.Context) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SystemRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFolder = `-- name: UpsertFolder :one
INSERT INTO folders (
  id, parent_id, name, system_role, sort_order, created_at, updated_at
) VALUES (
  ?1, ?2, ?3,
  ?4, ?5, ?6,
  ?7
)
ON CONFLICT(id) DO UPDATE SET
  parent_id = excluded.parent_id,
  name = excluded.name,
  system_role = excluded.system_role,
  sort_order = excluded.sort_order,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at
RETURNING id, parent_id, name, sort_order, created_at, updated_at, system_role
`

type UpsertFolderParams struct {
	ID         string         `json:"id"`
	ParentID   sql.NullString `json:"parent_id"`
	Name       string         `json:"name"`
	SystemRole sql.NullString `json:"system_role"`
	SortOrder  int64          `json:"sort_order"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
}

func (q *Queries) UpsertFolder(ctx context.Context, arg UpsertFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, upsertFolder,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.SystemRole,
		arg.SortOrder,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SystemRole,
	)
	return i, err
}
