// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const claimQueuedJob = `-- name: ClaimQueuedJob :one
UPDATE jobs
SET status = 'running',
    error = NULL,
    attempts = attempts + 1,
    updated_at = ?1,
    started_at = ?1,
    finished_at = NULL
WHERE id = (
  SELECT queued.id FROM jobs AS queued
  WHERE queued.status = 'queued'
    AND (
      queued.kind = ?2 OR
      queued.kind = ?3 OR
      queued.kind = ?4 OR
      queued.kind = ?5
    )
  ORDER BY queued.created_at ASC, queued.id ASC
  LIMIT 1
)
RETURNING id, kind, status, payload_json, error, attempts, created_at, updated_at, started_at, finished_at
`

type ClaimQueuedJobParams struct {
	Now   int64          `json:"now"`
	Kind1 sql.NullString `json:"kind_1"`
	Kind2 sql.NullString `json:"kind_2"`
	Kind3 sql.NullString `json:"kind_3"`
	Kind4 sql.NullString `json:"kind_4"`
}

func (q *Queries) ClaimQueuedJob(ctx context.Context, arg ClaimQueuedJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, claimQueuedJob,
		arg.Now,
		arg.Kind1,
		arg.Kind2,
		arg.Kind3,
		arg.Kind4,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.PayloadJson,
		&i.Error,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
  id, kind, status, payload_json, error, attempts, created_at, updated_at,
  started_at, finished_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10
) RETURNING id, kind, status, payload_json, error, attempts, created_at, updated_at, started_at, finished_at
`

type CreateJobParams struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	Status      string         `json:"status"`
	PayloadJson string         `json:"payload_json"`
	Error       sql.NullString `json:"error"`
	Attempts    int64          `json:"attempts"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
	StartedAt   sql.NullInt64  `json:"started_at"`
	FinishedAt  sql.NullInt64  `json:"finished_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJob,
		arg.ID,
		arg.Kind,
		arg.Status,
		arg.PayloadJson,
		arg.Error,
		arg.Attempts,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.PayloadJson,
		&i.Error,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const enqueueJob = `-- name: EnqueueJob :one
INSERT INTO jobs (
  id, kind, status, payload_json, error, attempts, created_at, updated_at,
  started_at, finished_at
) VALUES (
  ?1, ?2, 'queued', ?3,
  NULL, 0, ?4, ?4, NULL, NULL
)
ON CONFLICT(id) DO NOTHING
RETURNING id, kind, status, payload_json, error, attempts, created_at, updated_at, started_at, finished_at
`

type EnqueueJobParams struct {
	ID          string `json:"id"`
	Kind        string `json:"kind"`
	PayloadJson string `json:"payload_json"`
	Now         int64  `json:"now"`
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, enqueueJob,
		arg.ID,
		arg.Kind,
		arg.PayloadJson,
		arg.Now,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.PayloadJson,
		&i.Error,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, kind, status, payload_json, error, attempts, created_at, updated_at, started_at, finished_at FROM jobs WHERE id = ?1
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.PayloadJson,
		&i.Error,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, kind, status, payload_json, error, attempts, created_at, updated_at, started_at, finished_at FROM jobs
WHERE (?1 IS NULL OR status = ?1)
  AND (?2 IS NULL OR kind = ?2)
ORDER BY created_at DESC, id DESC
LIMIT ?3
`

type ListJobsParams struct {
	Status interface{} `json:"status"`
	Kind   interface{} `json:"kind"`
	Limit  int64       `json:"limit"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, arg.Status, arg.Kind, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.PayloadJson,
			&i.Error,
			&i.Attempts,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recoverRunningJobs = `-- name: RecoverRunningJobs :exec
UPDATE jobs
SET status = ?1,
    error = ?2,
    updated_at = ?3,
    finished_at = ?4
WHERE status = 'running'
`

type RecoverRunningJobsParams struct {
	Status     string         `json:"status"`
	Error      sql.NullString `json:"error"`
	UpdatedAt  int64          `json:"updated_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
}

func (q *Queries) RecoverRunningJobs(ctx context.Context, arg RecoverRunningJobsParams) error {
	_, err := q.db.ExecContext(ctx, recoverRunningJobs,
		arg.Status,
		arg.Error,
		arg.UpdatedAt,
		arg.FinishedAt,
	)
	return err
}

const schemaVersion = `-- name: SchemaVersion :one
SELECT CAST(COALESCE(MAX(version), 0) AS INTEGER) AS version FROM schema_migrations
`

func (q *Queries) SchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, schemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const updateJobState = `-- name: UpdateJobState :one
UPDATE jobs
SET status = ?1,
    error = ?2,
    attempts = ?3,
    updated_at = ?4,
    started_at = ?5,
    finished_at = ?6
WHERE id = ?7
RETURNING id, kind, status, payload_json, error, attempts, created_at, updated_at, started_at, finished_at
`

type UpdateJobStateParams struct {
	Status     string         `json:"status"`
	Error      sql.NullString `json:"error"`
	Attempts   int64          `json:"attempts"`
	UpdatedAt  int64          `json:"updated_at"`
	StartedAt  sql.NullInt64  `json:"started_at"`
	FinishedAt sql.NullInt64  `json:"finished_at"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateJobState(ctx context.Context, arg UpdateJobStateParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJobState,
		arg.Status,
		arg.Error,
		arg.Attempts,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.PayloadJson,
		&i.Error,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const upsertJob = `-- name: UpsertJob :one
INSERT INTO jobs (
  id, kind, status, payload_json, error, attempts, created_at, updated_at,
  started_at, finished_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7,
  ?8, ?9, ?10
)
ON CONFLICT(id) DO UPDATE SET
  kind = excluded.kind,
  status = excluded.status,
  payload_json = excluded.payload_json,
  error = excluded.error,
  attempts = excluded.attempts,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  started_at = excluded.started_at,
  finished_at = excluded.finished_at
RETURNING id, kind, status, payload_json, error, attempts, created_at, updated_at, started_at, finished_at
`

type UpsertJobParams struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	Status      string         `json:"status"`
	PayloadJson string         `json:"payload_json"`
	Error       sql.NullString `json:"error"`
	Attempts    int64          `json:"attempts"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
	StartedAt   sql.NullInt64  `json:"started_at"`
	FinishedAt  sql.NullInt64  `json:"finished_at"`
}

func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, upsertJob,
		arg.ID,
		arg.Kind,
		arg.Status,
		arg.PayloadJson,
		arg.Error,
		arg.Attempts,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.PayloadJson,
		&i.Error,
		&i.Attempts,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
