// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"database/sql"
)

type AppSequence struct {
	Name  string `json:"name"`
	Value int64  `json:"value"`
}

type AppSetting struct {
	ID                      int64         `json:"id"`
	FeedSchedulerEnabled    int64         `json:"feed_scheduler_enabled"`
	FeedPollIntervalSeconds int64         `json:"feed_poll_interval_seconds"`
	UpdatedAt               int64         `json:"updated_at"`
	FeedNextPollAt          sql.NullInt64 `json:"feed_next_poll_at"`
}

type Blob struct {
	ID         string `json:"id"`
	DocumentID string `json:"document_id"`
	Filename   string `json:"filename"`
	MimeType   string `json:"mime_type"`
	Size       int64  `json:"size"`
	Sha256     string `json:"sha256"`
	Data       []byte `json:"data"`
	CreatedAt  int64  `json:"created_at"`
}

type Document struct {
	ID           string         `json:"id"`
	Title        string         `json:"title"`
	Kind         string         `json:"kind"`
	FolderID     sql.NullString `json:"folder_id"`
	CanonicalUrl sql.NullString `json:"canonical_url"`
	SourceUrl    sql.NullString `json:"source_url"`
	Language     sql.NullString `json:"language"`
	Status       string         `json:"status"`
	Rating       sql.NullInt64  `json:"rating"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	ReadAt       sql.NullInt64  `json:"read_at"`
	DeletedAt    sql.NullInt64  `json:"deleted_at"`
}

type DocumentContent struct {
	ID              string         `json:"id"`
	DocumentID      string         `json:"document_id"`
	Role            string         `json:"role"`
	Format          string         `json:"format"`
	Language        sql.NullString `json:"language"`
	Content         string         `json:"content"`
	SourceContentID sql.NullString `json:"source_content_id"`
	CreatedAt       int64          `json:"created_at"`
}

type DocumentNote struct {
	ID         string        `json:"id"`
	DocumentID string        `json:"document_id"`
	Body       string        `json:"body"`
	Format     string        `json:"format"`
	CreatedAt  int64         `json:"created_at"`
	UpdatedAt  int64         `json:"updated_at"`
	DeletedAt  sql.NullInt64 `json:"deleted_at"`
}

type DocumentTag struct {
	DocumentID string `json:"document_id"`
	TagID      string `json:"tag_id"`
}

type DocumentVersion struct {
	ID                   string `json:"id"`
	DocumentID           string `json:"document_id"`
	Sequence             int64  `json:"sequence"`
	MutationKind         string `json:"mutation_kind"`
	Title                string `json:"title"`
	ContentSnapshotJson  string `json:"content_snapshot_json"`
	MetadataSnapshotJson string `json:"metadata_snapshot_json"`
	CreatedAt            int64  `json:"created_at"`
}

type DocumentsFt struct {
	DocumentID string `json:"document_id"`
	Title      string `json:"title"`
	Body       string `json:"body"`
}

type Feed struct {
	ID            string         `json:"id"`
	Url           string         `json:"url"`
	Title         sql.NullString `json:"title"`
	FolderID      sql.NullString `json:"folder_id"`
	Enabled       int64          `json:"enabled"`
	LastCheckedAt sql.NullInt64  `json:"last_checked_at"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
}

type FeedItem struct {
	ID           string         `json:"id"`
	FeedID       string         `json:"feed_id"`
	DocumentID   string         `json:"document_id"`
	Guid         sql.NullString `json:"guid"`
	Url          string         `json:"url"`
	CanonicalUrl sql.NullString `json:"canonical_url"`
	ContentHash  sql.NullString `json:"content_hash"`
	PublishedAt  sql.NullInt64  `json:"published_at"`
	CreatedAt    int64          `json:"created_at"`
}

type Folder struct {
	ID         string         `json:"id"`
	ParentID   sql.NullString `json:"parent_id"`
	Name       string         `json:"name"`
	SortOrder  int64          `json:"sort_order"`
	CreatedAt  int64          `json:"created_at"`
	UpdatedAt  int64          `json:"updated_at"`
	SystemRole sql.NullString `json:"system_role"`
}

type Job struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	Status      string         `json:"status"`
	PayloadJson string         `json:"payload_json"`
	Error       sql.NullString `json:"error"`
	Attempts    int64          `json:"attempts"`
	CreatedAt   int64          `json:"created_at"`
	UpdatedAt   int64          `json:"updated_at"`
	StartedAt   sql.NullInt64  `json:"started_at"`
	FinishedAt  sql.NullInt64  `json:"finished_at"`
}

type SchemaMigration struct {
	Version   int64  `json:"version"`
	Name      string `json:"name"`
	AppliedAt int64  `json:"applied_at"`
}

type Tag struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt int64  `json:"created_at"`
}
