// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const createDocumentNote = `-- name: CreateDocumentNote :one
INSERT INTO document_notes (
  id, document_id, body, format, created_at, updated_at, deleted_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7
) RETURNING id, document_id, body, format, created_at, updated_at, deleted_at
`

type CreateDocumentNoteParams struct {
	ID         string        `json:"id"`
	DocumentID string        `json:"document_id"`
	Body       string        `json:"body"`
	Format     string        `json:"format"`
	CreatedAt  int64         `json:"created_at"`
	UpdatedAt  int64         `json:"updated_at"`
	DeletedAt  sql.NullInt64 `json:"deleted_at"`
}

func (q *Queries) CreateDocumentNote(ctx context.Context, arg CreateDocumentNoteParams) (DocumentNote, error) {
	row := q.db.QueryRowContext(ctx, createDocumentNote,
		arg.ID,
		arg.DocumentID,
		arg.Body,
		arg.Format,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i DocumentNote
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Body,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDocumentNote = `-- name: GetDocumentNote :one
SELECT id, document_id, body, format, created_at, updated_at, deleted_at FROM document_notes
WHERE document_id = ?1
  AND id = ?2
`

type GetDocumentNoteParams struct {
	DocumentID string `json:"document_id"`
	ID         string `json:"id"`
}

func (q *Queries) GetDocumentNote(ctx context.Context, arg GetDocumentNoteParams) (DocumentNote, error) {
	row := q.db.QueryRowContext(ctx, getDocumentNote, arg.DocumentID, arg.ID)
	var i DocumentNote
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Body,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDocumentNotes = `-- name: ListDocumentNotes :many
SELECT id, document_id, body, format, created_at, updated_at, deleted_at FROM document_notes
WHERE document_id = ?1
  AND deleted_at IS NULL
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListDocumentNotes(ctx context.Context, documentID string) ([]DocumentNote, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentNotes, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentNote{}
	for rows.Next() {
		var i DocumentNote
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Body,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentNotesAll = `-- name: ListDocumentNotesAll :many
SELECT id, document_id, body, format, created_at, updated_at, deleted_at FROM document_notes
WHERE document_id = ?1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListDocumentNotesAll(ctx context.Context, documentID string) ([]DocumentNote, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentNotesAll, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentNote{}
	for rows.Next() {
		var i DocumentNote
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Body,
			&i.Format,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDocumentNote = `-- name: SoftDeleteDocumentNote :one
UPDATE document_notes
SET deleted_at = ?1,
    updated_at = ?2
WHERE id = ?3
  AND document_id = ?4
RETURNING id, document_id, body, format, created_at, updated_at, deleted_at
`

type SoftDeleteDocumentNoteParams struct {
	DeletedAt  sql.NullInt64 `json:"deleted_at"`
	UpdatedAt  int64         `json:"updated_at"`
	ID         string        `json:"id"`
	DocumentID string        `json:"document_id"`
}

func (q *Queries) SoftDeleteDocumentNote(ctx context.Context, arg SoftDeleteDocumentNoteParams) (DocumentNote, error) {
	row := q.db.QueryRowContext(ctx, softDeleteDocumentNote,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID,
		arg.DocumentID,
	)
	var i DocumentNote
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Body,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDocumentNote = `-- name: UpdateDocumentNote :one
UPDATE document_notes
SET body = ?1,
    format = ?2,
    updated_at = ?3
WHERE id = ?4
  AND document_id = ?5
  AND deleted_at IS NULL
RETURNING id, document_id, body, format, created_at, updated_at, deleted_at
`

type UpdateDocumentNoteParams struct {
	Body       string `json:"body"`
	Format     string `json:"format"`
	UpdatedAt  int64  `json:"updated_at"`
	ID         string `json:"id"`
	DocumentID string `json:"document_id"`
}

func (q *Queries) UpdateDocumentNote(ctx context.Context, arg UpdateDocumentNoteParams) (DocumentNote, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentNote,
		arg.Body,
		arg.Format,
		arg.UpdatedAt,
		arg.ID,
		arg.DocumentID,
	)
	var i DocumentNote
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Body,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertDocumentNote = `-- name: UpsertDocumentNote :one
INSERT INTO document_notes (
  id, document_id, body, format, created_at, updated_at, deleted_at
) VALUES (
  ?1, ?2, ?3, ?4,
  ?5, ?6, ?7
)
ON CONFLICT(id) DO UPDATE SET
  document_id = excluded.document_id,
  body = excluded.body,
  format = excluded.format,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  deleted_at = excluded.deleted_at
RETURNING id, document_id, body, format, created_at, updated_at, deleted_at
`

type UpsertDocumentNoteParams struct {
	ID         string        `json:"id"`
	DocumentID string        `json:"document_id"`
	Body       string        `json:"body"`
	Format     string        `json:"format"`
	CreatedAt  int64         `json:"created_at"`
	UpdatedAt  int64         `json:"updated_at"`
	DeletedAt  sql.NullInt64 `json:"deleted_at"`
}

func (q *Queries) UpsertDocumentNote(ctx context.Context, arg UpsertDocumentNoteParams) (DocumentNote, error) {
	row := q.db.QueryRowContext(ctx, upsertDocumentNote,
		arg.ID,
		arg.DocumentID,
		arg.Body,
		arg.Format,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	var i DocumentNote
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Body,
		&i.Format,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
