// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitedb

import (
	"context"
)

type Querier interface {
	AssignDocumentTag(ctx context.Context, arg AssignDocumentTagParams) error
	ClaimQueuedJob(ctx context.Context, arg ClaimQueuedJobParams) (Job, error)
	CountDocumentIDs(ctx context.Context, arg CountDocumentIDsParams) (int64, error)
	CountSearchDocumentIDs(ctx context.Context, arg CountSearchDocumentIDsParams) (int64, error)
	CreateBlob(ctx context.Context, arg CreateBlobParams) (Blob, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateDocumentContent(ctx context.Context, arg CreateDocumentContentParams) (DocumentContent, error)
	CreateDocumentNote(ctx context.Context, arg CreateDocumentNoteParams) (DocumentNote, error)
	CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error)
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateFeedItem(ctx context.Context, arg CreateFeedItemParams) (FeedItem, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	DeleteDocumentBlobs(ctx context.Context, documentID string) error
	DeleteDocumentContents(ctx context.Context, documentID string) error
	DeleteDocumentTags(ctx context.Context, documentID string) error
	DeleteFeed(ctx context.Context, id string) error
	DeleteFolder(ctx context.Context, id string) error
	DeleteTag(ctx context.Context, id string) error
	EnqueueJob(ctx context.Context, arg EnqueueJobParams) (Job, error)
	GetAppSettings(ctx context.Context) (AppSetting, error)
	GetDocument(ctx context.Context, id string) (Document, error)
	GetDocumentNote(ctx context.Context, arg GetDocumentNoteParams) (DocumentNote, error)
	GetFeed(ctx context.Context, id string) (Feed, error)
	GetFeedByURL(ctx context.Context, url string) (Feed, error)
	GetFeedItemByDocumentID(ctx context.Context, documentID string) (FeedItem, error)
	GetFolder(ctx context.Context, id string) (Folder, error)
	GetJob(ctx context.Context, id string) (Job, error)
	GetTag(ctx context.Context, id string) (Tag, error)
	GetTagBySlug(ctx context.Context, slug string) (Tag, error)
	ListDocumentBlobs(ctx context.Context, documentID string) ([]Blob, error)
	ListDocumentContents(ctx context.Context, documentID string) ([]DocumentContent, error)
	ListDocumentIDsCreatedDesc(ctx context.Context, arg ListDocumentIDsCreatedDescParams) ([]string, error)
	ListDocumentIDsRatingDesc(ctx context.Context, arg ListDocumentIDsRatingDescParams) ([]string, error)
	ListDocumentIDsRecent(ctx context.Context, arg ListDocumentIDsRecentParams) ([]string, error)
	ListDocumentNotes(ctx context.Context, documentID string) ([]DocumentNote, error)
	ListDocumentNotesAll(ctx context.Context, documentID string) ([]DocumentNote, error)
	ListDocumentTags(ctx context.Context, documentID string) ([]Tag, error)
	ListDocumentVersions(ctx context.Context, documentID string) ([]DocumentVersion, error)
	ListDocuments(ctx context.Context) ([]Document, error)
	ListFeedItems(ctx context.Context, feedID string) ([]FeedItem, error)
	ListFeeds(ctx context.Context) ([]Feed, error)
	ListFolders(ctx context.Context) ([]Folder, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListTags(ctx context.Context) ([]Tag, error)
	NextSequence(ctx context.Context, name string) (int64, error)
	RecoverRunningJobs(ctx context.Context, arg RecoverRunningJobsParams) error
	SchemaVersion(ctx context.Context) (int64, error)
	SearchDocumentIDsCreatedDesc(ctx context.Context, arg SearchDocumentIDsCreatedDescParams) ([]string, error)
	SearchDocumentIDsRatingDesc(ctx context.Context, arg SearchDocumentIDsRatingDescParams) ([]string, error)
	SearchDocumentIDsRecent(ctx context.Context, arg SearchDocumentIDsRecentParams) ([]string, error)
	SearchDocumentIDsRelevance(ctx context.Context, arg SearchDocumentIDsRelevanceParams) ([]string, error)
	SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) (Document, error)
	SoftDeleteDocumentNote(ctx context.Context, arg SoftDeleteDocumentNoteParams) (DocumentNote, error)
	TagHasDocuments(ctx context.Context, tagID string) (int64, error)
	UpdateDocumentMetadata(ctx context.Context, arg UpdateDocumentMetadataParams) (Document, error)
	UpdateDocumentNote(ctx context.Context, arg UpdateDocumentNoteParams) (DocumentNote, error)
	UpdateJobState(ctx context.Context, arg UpdateJobStateParams) (Job, error)
	UpsertAppSettings(ctx context.Context, arg UpsertAppSettingsParams) (AppSetting, error)
	UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (Document, error)
	UpsertDocumentNote(ctx context.Context, arg UpsertDocumentNoteParams) (DocumentNote, error)
	UpsertFeed(ctx context.Context, arg UpsertFeedParams) (Feed, error)
	UpsertFeedItem(ctx context.Context, arg UpsertFeedItemParams) (FeedItem, error)
	UpsertFolder(ctx context.Context, arg UpsertFolderParams) (Folder, error)
	UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error)
	UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error)
}

var _ Querier = (*Queries)(nil)
