// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sequence.sql

package sqlitedb

import (
	"context"
)

const nextSequence = `-- name: NextSequence :one
INSERT INTO app_sequence (name, value)
VALUES (?1, 1)
ON CONFLICT(name) DO UPDATE SET value = value + 1
RETURNING value
`

func (q *Queries) NextSequence(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextSequence, name)
	var value int64
	err := row.Scan(&value)
	return value, err
}
