// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlitedb

import (
	"context"
	"database/sql"
)

const getAppSettings = `-- name: GetAppSettings :one
SELECT id, feed_scheduler_enabled, feed_poll_interval_seconds, updated_at, feed_next_poll_at FROM app_settings WHERE id = 1
`

func (q *Queries) GetAppSettings(ctx context.Context) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getAppSettings)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.FeedSchedulerEnabled,
		&i.FeedPollIntervalSeconds,
		&i.UpdatedAt,
		&i.FeedNextPollAt,
	)
	return i, err
}

const upsertAppSettings = `-- name: UpsertAppSettings :one
INSERT INTO app_settings (
  id, feed_scheduler_enabled, feed_poll_interval_seconds, feed_next_poll_at, updated_at
) VALUES (
  1, ?1,
  ?2, ?3,
  ?4
)
ON CONFLICT(id) DO UPDATE SET
  feed_scheduler_enabled = excluded.feed_scheduler_enabled,
  feed_poll_interval_seconds = excluded.feed_poll_interval_seconds,
  feed_next_poll_at = excluded.feed_next_poll_at,
  updated_at = excluded.updated_at
RETURNING id, feed_scheduler_enabled, feed_poll_interval_seconds, updated_at, feed_next_poll_at
`

type UpsertAppSettingsParams struct {
	FeedSchedulerEnabled    int64         `json:"feed_scheduler_enabled"`
	FeedPollIntervalSeconds int64         `json:"feed_poll_interval_seconds"`
	FeedNextPollAt          sql.NullInt64 `json:"feed_next_poll_at"`
	UpdatedAt               int64         `json:"updated_at"`
}

func (q *Queries) UpsertAppSettings(ctx context.Context, arg UpsertAppSettingsParams) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, upsertAppSettings,
		arg.FeedSchedulerEnabled,
		arg.FeedPollIntervalSeconds,
		arg.FeedNextPollAt,
		arg.UpdatedAt,
	)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.FeedSchedulerEnabled,
		&i.FeedPollIntervalSeconds,
		&i.UpdatedAt,
		&i.FeedNextPollAt,
	)
	return i, err
}
