// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlitedb

import (
	"context"
)

const assignDocumentTag = `-- name: AssignDocumentTag :exec
INSERT INTO document_tags (document_id, tag_id)
VALUES (?1, ?2)
`

type AssignDocumentTagParams struct {
	DocumentID string `json:"document_id"`
	TagID      string `json:"tag_id"`
}

func (q *Queries) AssignDocumentTag(ctx context.Context, arg AssignDocumentTagParams) error {
	_, err := q.db.ExecContext(ctx, assignDocumentTag, arg.DocumentID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (id, name, slug, created_at)
VALUES (?1, ?2, ?3, ?4)
RETURNING id, name, slug, created_at
`

type CreateTagParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocumentTags = `-- name: DeleteDocumentTags :exec
DELETE FROM document_tags WHERE document_id = ?1
`

func (q *Queries) DeleteDocumentTags(ctx context.Context, documentID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentTags, documentID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?1
`

func (q *Queries) DeleteTag(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, slug, created_at FROM tags WHERE id = ?1
`

func (q *Queries) GetTag(ctx context.Context, id string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, name, slug, created_at FROM tags WHERE slug = ?1
`

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTagBySlug, slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentTags = `-- name: ListDocumentTags :many
SELECT tags.id, tags.name, tags.slug, tags.created_at FROM tags
JOIN document_tags ON document_tags.tag_id = tags.id
WHERE document_tags.document_id = ?1
ORDER BY tags.slug ASC
`

func (q *Queries) ListDocumentTags(ctx context.Context, documentID string) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listDocumentTags, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, slug, created_at FROM tags ORDER BY slug ASC, id ASC
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tagHasDocuments = `-- name: TagHasDocuments :one
SELECT 1 FROM document_tags
WHERE tag_id = ?1
LIMIT 1
`

func (q *Queries) TagHasDocuments(ctx context.Context, tagID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, tagHasDocuments, tagID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (id, name, slug, created_at)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  slug = excluded.slug,
  created_at = excluded.created_at
RETURNING id, name, slug, created_at
`

type UpsertTagParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, upsertTag,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
