package reportilphase0

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/c86j224s/liquid2/plasma/internal/pdfdocument"
)

var runIDPattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$`)

// RunConfig defines one immutable archive-local Phase 0 compilation.
type RunConfig struct {
	ArchiveRoot    string
	RepositoryRoot string
	BundlePath     string
	RunID          string
	PDFRenderer    PDFRenderer
	RequirePDF     bool
}

// RunResult names the generated durable archive artifacts.
type RunResult struct {
	RunDirectory string
	ManifestPath string
	MarkdownPath string
	HTMLPath     string
	PDFPath      string
	BlockerPath  string
	Manifest     Manifest
}

// Manifest binds one accepted input to every target artifact and degradation
// outcome generated by this experimental compiler.
type Manifest struct {
	SchemaVersion     string               `json:"schema_version"`
	CompilerVersion   string               `json:"compiler_version"`
	PipelineFamily    string               `json:"pipeline_family"`
	RunID             string               `json:"run_id"`
	Arm               string               `json:"arm"`
	CreatedAt         string               `json:"created_at"`
	Bundle            ArtifactReceipt      `json:"bundle"`
	NarrativeContract *ArtifactReceipt     `json:"narrative_contract,omitempty"`
	SemanticIL        ArtifactReceipt      `json:"semantic_il"`
	LinearProjection  ArtifactReceipt      `json:"linear_projection"`
	FlowAttestation   *ArtifactReceipt     `json:"flow_attestation,omitempty"`
	Targets           []TargetReceipt      `json:"targets"`
	Degradations      []DegradationReceipt `json:"degradations,omitempty"`
	PDFRenderer       *PDFRendererReceipt  `json:"pdf_renderer,omitempty"`
	PDFBlocker        *BlockerReceipt      `json:"pdf_blocker,omitempty"`
}

type ArtifactReceipt struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
}

type TargetReceipt struct {
	Target    string `json:"target"`
	MediaType string `json:"media_type"`
	Path      string `json:"path"`
	SHA256    string `json:"sha256"`
	ByteSize  int    `json:"byte_size"`
}

type PDFRendererReceipt struct {
	Product  string `json:"product"`
	Revision string `json:"revision"`
	Tagged   bool   `json:"tagged_requested"`
	Outline  bool   `json:"outline_requested"`
}

type BlockerReceipt struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Run validates all inputs before creating a new archive directory, compiles
// deterministic textual targets, and either records a valid PDF or an explicit
// preflight blocker.
func Run(ctx context.Context, config RunConfig) (RunResult, error) {
	validated, err := validateRunConfig(config)
	if err != nil {
		return RunResult{}, err
	}
	raw, err := os.ReadFile(validated.BundlePath)
	if err != nil {
		return RunResult{}, err
	}
	bundle, err := LoadBundle(raw)
	if err != nil {
		return RunResult{}, err
	}
	markdown, markdownDegradations, err := RenderMarkdown(bundle.Document)
	if err != nil {
		return RunResult{}, err
	}
	htmlContent, htmlDegradations, err := RenderHTML(bundle.Document)
	if err != nil {
		return RunResult{}, err
	}

	runsDir, err := prepareRunsDirectory(validated.ArchiveRoot, validated.RepositoryRoot)
	if err != nil {
		return RunResult{}, err
	}
	runDir := filepath.Join(runsDir, validated.RunID)
	if err := os.Mkdir(runDir, 0o700); err != nil {
		if os.IsExist(err) {
			return RunResult{}, fmt.Errorf("run directory already exists: %s", runDir)
		}
		return RunResult{}, err
	}

	result := RunResult{RunDirectory: runDir}
	if err := writeNewFile(filepath.Join(runDir, "input-bundle.json"), raw); err != nil {
		return result, err
	}
	if err := writeRunInputs(runDir, bundle); err != nil {
		return result, err
	}
	result.MarkdownPath = filepath.Join(runDir, "report.md")
	result.HTMLPath = filepath.Join(runDir, "report.html")
	if err := writeNewFile(result.MarkdownPath, markdown); err != nil {
		return result, err
	}
	if err := writeNewFile(result.HTMLPath, htmlContent); err != nil {
		return result, err
	}

	semanticILReceipt, err := artifactReceipt(filepath.Join(runDir, "semantic-il.json"))
	if err != nil {
		return result, err
	}
	manifest := Manifest{
		SchemaVersion:    ManifestSchemaVersion,
		CompilerVersion:  CompilerVersion,
		PipelineFamily:   PipelineFamily,
		RunID:            validated.RunID,
		Arm:              bundle.Arm,
		CreatedAt:        time.Now().UTC().Format(time.RFC3339Nano),
		Bundle:           ArtifactReceipt{Path: "input-bundle.json", SHA256: SHA256(raw)},
		SemanticIL:       semanticILReceipt,
		LinearProjection: ArtifactReceipt{Path: filepath.Base(result.MarkdownPath), SHA256: SHA256(markdown)},
		Degradations:     append(markdownDegradations, htmlDegradations...),
		Targets: []TargetReceipt{
			targetReceipt("markdown", "text/markdown; charset=utf-8", result.MarkdownPath, markdown),
			targetReceipt("html", "text/html; charset=utf-8", result.HTMLPath, htmlContent),
		},
	}
	if bundle.Narrative != nil {
		receipt, err := artifactReceipt(filepath.Join(runDir, "narrative-contract.json"))
		if err != nil {
			return result, err
		}
		manifest.NarrativeContract = &receipt
	}
	if bundle.Attestation != nil {
		receipt, err := artifactReceipt(filepath.Join(runDir, "flow-attestation.json"))
		if err != nil {
			return result, err
		}
		manifest.FlowAttestation = &receipt
	}

	if validated.PDFRenderer == nil {
		return result, fmt.Errorf("PDF renderer is not configured")
	}
	pdfResult, pdfErr := validated.PDFRenderer.RenderPDF(ctx, htmlContent)
	if pdfErr != nil {
		blocker := BlockerReceipt{Code: "pdf_renderer_unavailable", Message: pdfErr.Error()}
		manifest.PDFBlocker = &blocker
		result.BlockerPath = filepath.Join(runDir, "pdf-blocker.json")
		if err := writeJSON(result.BlockerPath, blocker); err != nil {
			return result, err
		}
		if validated.RequirePDF {
			result.Manifest = manifest
			if err := writeManifest(runDir, &result); err != nil {
				return result, err
			}
			return result, fmt.Errorf("required PDF target failed: %w", pdfErr)
		}
	} else {
		if _, err := pdfdocument.Inspect(pdfResult.Content); err != nil {
			return result, fmt.Errorf("inspect generated PDF: %w", err)
		}
		result.PDFPath = filepath.Join(runDir, "report.pdf")
		if err := writeNewFile(result.PDFPath, pdfResult.Content); err != nil {
			return result, err
		}
		manifest.Targets = append(manifest.Targets, targetReceipt("pdf", pdfdocument.MediaType, result.PDFPath, pdfResult.Content))
		manifest.PDFRenderer = &PDFRendererReceipt{Product: pdfResult.RendererProduct, Revision: pdfResult.RendererRevision, Tagged: true, Outline: true}
	}
	result.Manifest = manifest
	if err := writeManifest(runDir, &result); err != nil {
		return result, err
	}
	return result, nil
}

type validatedRunConfig struct {
	ArchiveRoot    string
	RepositoryRoot string
	BundlePath     string
	RunID          string
	PDFRenderer    PDFRenderer
	RequirePDF     bool
}

func validateRunConfig(config RunConfig) (validatedRunConfig, error) {
	if !runIDPattern.MatchString(strings.TrimSpace(config.RunID)) || strings.Contains(config.RunID, "..") {
		return validatedRunConfig{}, fmt.Errorf("run ID must be a safe slug")
	}
	archive, err := canonicalForCreate(config.ArchiveRoot)
	if err != nil {
		return validatedRunConfig{}, err
	}
	repo, err := canonicalExisting(config.RepositoryRoot)
	if err != nil {
		return validatedRunConfig{}, err
	}
	if pathInside(repo, archive) {
		return validatedRunConfig{}, fmt.Errorf("archive root must stay outside the repository")
	}
	bundle, err := canonicalExisting(config.BundlePath)
	if err != nil {
		return validatedRunConfig{}, err
	}
	if !pathInside(archive, bundle) || pathInside(repo, bundle) {
		return validatedRunConfig{}, fmt.Errorf("bundle must be under archive root and outside the repository")
	}
	if err := os.MkdirAll(archive, 0o700); err != nil {
		return validatedRunConfig{}, err
	}
	archive, err = canonicalExisting(archive)
	if err != nil {
		return validatedRunConfig{}, err
	}
	return validatedRunConfig{ArchiveRoot: archive, RepositoryRoot: repo, BundlePath: bundle, RunID: strings.TrimSpace(config.RunID), PDFRenderer: config.PDFRenderer, RequirePDF: config.RequirePDF}, nil
}

func prepareRunsDirectory(archiveRoot, repositoryRoot string) (string, error) {
	runsDir := filepath.Join(archiveRoot, "runs")
	if err := os.MkdirAll(runsDir, 0o700); err != nil {
		return "", err
	}
	resolved, err := canonicalExisting(runsDir)
	if err != nil {
		return "", err
	}
	if !pathInside(archiveRoot, resolved) || pathInside(repositoryRoot, resolved) {
		return "", fmt.Errorf("runs directory must remain under archive root and outside the repository")
	}
	return resolved, nil
}

func writeRunInputs(runDir string, bundle Bundle) error {
	if bundle.Narrative != nil {
		if err := writeJSON(filepath.Join(runDir, "narrative-contract.json"), bundle.Narrative); err != nil {
			return err
		}
	}
	if err := writeJSON(filepath.Join(runDir, "semantic-il.json"), bundle.Document); err != nil {
		return err
	}
	if bundle.Attestation != nil {
		if err := writeJSON(filepath.Join(runDir, "flow-attestation.json"), bundle.Attestation); err != nil {
			return err
		}
	}
	return nil
}

func writeManifest(runDir string, result *RunResult) error {
	result.ManifestPath = filepath.Join(runDir, "manifest.json")
	return writeJSON(result.ManifestPath, result.Manifest)
}

func writeJSON(path string, value any) error {
	raw, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	return writeNewFile(path, append(raw, '\n'))
}

func writeNewFile(path string, content []byte) (err error) {
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		return err
	}
	defer func() {
		if closeErr := file.Close(); err == nil {
			err = closeErr
		}
	}()
	_, err = file.Write(content)
	return err
}

func artifactReceipt(path string) (ArtifactReceipt, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return ArtifactReceipt{}, err
	}
	return ArtifactReceipt{Path: filepath.Base(path), SHA256: SHA256(raw)}, nil
}

func targetReceipt(target, mediaType, path string, content []byte) TargetReceipt {
	return TargetReceipt{Target: target, MediaType: mediaType, Path: filepath.Base(path), SHA256: SHA256(content), ByteSize: len(content)}
}

func canonicalExisting(path string) (string, error) {
	if strings.TrimSpace(path) == "" {
		return "", fmt.Errorf("path is required")
	}
	absolute, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	return filepath.EvalSymlinks(absolute)
}

func canonicalForCreate(path string) (string, error) {
	if strings.TrimSpace(path) == "" {
		return "", fmt.Errorf("path is required")
	}
	absolute, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	ancestor := absolute
	missing := []string{}
	for {
		if _, err := os.Stat(ancestor); err == nil {
			break
		} else if !os.IsNotExist(err) {
			return "", err
		}
		parent := filepath.Dir(ancestor)
		if parent == ancestor {
			return "", fmt.Errorf("no existing archive ancestor")
		}
		missing = append([]string{filepath.Base(ancestor)}, missing...)
		ancestor = parent
	}
	resolved, err := filepath.EvalSymlinks(ancestor)
	if err != nil {
		return "", err
	}
	return filepath.Join(append([]string{resolved}, missing...)...), nil
}

func pathInside(root, candidate string) bool {
	relative, err := filepath.Rel(filepath.Clean(root), filepath.Clean(candidate))
	return err == nil && (relative == "." || (relative != ".." && !strings.HasPrefix(relative, ".."+string(os.PathSeparator))))
}
